### ISSUE TITLE
Fix tests of drake common

### ISSUE THREAD

**Issue by traversaro** [traversaro/drake-conda-forge-build#1]
drake common tests are currently working fine, expect for two:
~~~
2021-04-07T02:49:55.8620005Z [ RUN      ] SymbolicFormulaTest.Isinf
2021-04-07T02:49:55.8620856Z common/test/symbolic_formula_test.cc:1204: Failure
2021-04-07T02:49:55.8621613Z Expected equality of these values:
2021-04-07T02:49:55.8623054Z   std::isinf(-inf)
2021-04-07T02:49:55.8623586Z     Which is: -1
2021-04-07T02:49:55.8624237Z   isinf(Expression(-inf)).Evaluate()
2021-04-07T02:49:55.8624837Z     Which is: true
~~~

and 
~~~
2021-04-07T02:44:28.9252151Z [721 / 724] 20 / 108 tests; Testing //common/proto:call_python_test; 41s linux-sandbox ... (2 actions running)
2021-04-07T02:46:47.9750022Z 
2021-04-07T02:46:47.9754666Z TIMEOUT: //common/proto:call_python_test (Summary)
2021-04-07T02:46:47.9757048Z       /usr/share/miniconda/envs/test/share/bazel/f551a99aa469d1a26c94c9222028a656/execroot/drake/bazel-out/k8-opt/testlogs/common/proto/call_python_test/test.log
2021-04-07T02:46:47.9759395Z       /usr/share/miniconda/envs/test/share/bazel/f551a99aa469d1a26c94c9222028a656/execroot/drake/bazel-out/k8-opt/testlogs/common/proto/call_python_test/test_attempts/attempt_1.log
2021-04-07T02:46:47.9761717Z       /usr/share/miniconda/envs/test/share/bazel/f551a99aa469d1a26c94c9222028a656/execroot/drake/bazel-out/k8-opt/testlogs/common/proto/call_python_test/test_attempts/attempt_2.log
2021-04-07T02:46:47.9780951Z INFO: From Testing //common/proto:call_python_test:
2021-04-07T02:46:47.9792584Z ==================== Test output for //common/proto:call_python_test:
2021-04-07T02:46:47.9793342Z 
2021-04-07T02:46:47.9793958Z Running tests...
2021-04-07T02:46:47.9795161Z ----------------------------------------------------------------------
2021-04-07T02:46:47.9795997Z [ with_error: False ]
2021-04-07T02:46:47.9796710Z Using drake_cc_googletest_main.cc
2021-04-07T02:46:47.9797268Z 
2021-04-07T02:46:47.9797930Z [==========] Running 9 tests from 1 test suite.
2021-04-07T02:46:47.9798930Z [----------] Global test environment set-up.
2021-04-07T02:46:47.9799988Z [----------] 9 tests from TestCallPython
2021-04-07T02:46:47.9801117Z [ RUN      ] TestCallPython.Start
2021-04-07T02:46:47.9802634Z Traceback (most recent call last):
2021-04-07T02:46:47.9805043Z   File "/usr/share/miniconda/envs/test/share/bazel/f551a99aa469d1a26c94c9222028a656/sandbox/linux-sandbox/359/execroot/drake/bazel-out/k8-opt/bin/common/proto/call_python_test.runfiles/drake/common/proto/call_python_client.py", line 51, in <module>
2021-04-07T02:46:47.9806615Z     import numpy as np
2021-04-07T02:46:47.9807575Z ModuleNotFoundError: No module named 'numpy'
2021-04-07T02:46:47.9808595Z -- Test timed out at 2021-04-07 02:44:47 UTC --
2021-04-07T02:46:47.9809227Z ================================================================================
2021-04-07T02:46:47.9809959Z ==================== Test output for //common/proto:call_python_test:
2021-04-07T02:46:47.9810511Z 
2021-04-07T02:46:47.9811009Z Running tests...
2021-04-07T02:46:47.9811931Z ----------------------------------------------------------------------
2021-04-07T02:46:47.9812640Z [ with_error: False ]
2021-04-07T02:46:47.9813308Z Using drake_cc_googletest_main.cc
2021-04-07T02:46:47.9813796Z 
2021-04-07T02:46:47.9814357Z [==========] Running 9 tests from 1 test suite.
2021-04-07T02:46:47.9815294Z [----------] Global test environment set-up.
2021-04-07T02:46:47.9816250Z [----------] 9 tests from TestCallPython
2021-04-07T02:46:47.9817056Z [ RUN      ] TestCallPython.Start
2021-04-07T02:46:47.9817799Z Traceback (most recent call last):
2021-04-07T02:46:47.9819785Z   File "/usr/share/miniconda/envs/test/share/bazel/f551a99aa469d1a26c94c9222028a656/sandbox/linux-sandbox/385/execroot/drake/bazel-out/k8-opt/bin/common/proto/call_python_test.runfiles/drake/common/proto/call_python_client.py", line 51, in <module>
2021-04-07T02:46:47.9821292Z     import numpy as np
2021-04-07T02:46:47.9822245Z ModuleNotFoundError: No module named 'numpy'
2021-04-07T02:46:47.9823234Z -- Test timed out at 2021-04-07 02:45:47 UTC --
2021-04-07T02:46:47.9823883Z ================================================================================
2021-04-07T02:46:47.9824592Z ==================== Test output for //common/proto:call_python_test:
2021-04-07T02:46:47.9825151Z 
2021-04-07T02:46:47.9825830Z Running tests...
2021-04-07T02:46:47.9826767Z ----------------------------------------------------------------------
2021-04-07T02:46:47.9827477Z [ with_error: False ]
2021-04-07T02:46:47.9828177Z Using drake_cc_googletest_main.cc
2021-04-07T02:46:47.9831516Z 
2021-04-07T02:46:47.9831983Z [==========] Running 9 tests from 1 test suite.
2021-04-07T02:46:47.9832827Z [----------] Global test environment set-up.
2021-04-07T02:46:47.9833628Z [----------] 9 tests from TestCallPython
2021-04-07T02:46:47.9834303Z [ RUN      ] TestCallPython.Start
2021-04-07T02:46:47.9834921Z Traceback (most recent call last):
2021-04-07T02:46:47.9836770Z   File "/usr/share/miniconda/envs/test/share/bazel/f551a99aa469d1a26c94c9222028a656/sandbox/linux-sandbox/399/execroot/drake/bazel-out/k8-opt/bin/common/proto/call_python_test.runfiles/drake/common/proto/call_python_client.py", line 51, in <module>
2021-04-07T02:46:47.9838148Z     import numpy as np
2021-04-07T02:46:47.9838962Z ModuleNotFoundError: No module named 'numpy'
2021-04-07T02:46:47.9839795Z -- Test timed out at 2021-04-07 02:46:47 UTC --
2021-04-07T02:46:47.9840312Z ================================================================================
2021-04-07T02:47:22.0393540Z [837 / 842] 35 / 108 tests, 1 failed; Compiling common/test/symbolic_expression_test.cc; 28s linux-sandbox ... (2 actions running)
2021-04-07T02:49:55.8080725Z FAIL: //common:symbolic_formula_test (see /usr/share/miniconda/envs/test/share/bazel/f551a99aa469d1a26c94c9222028a656/execroot/drake/bazel-out/k8-opt/testlogs/common/symbolic_formula_test/test.log)
2021-04-07T02:49:55.8142770Z INFO: From Testing //common:symbolic_formula_test:
2021-04-07T02:49:55.8255161Z ==================== Test output for //common:symbolic_formula_test:
2021-04-07T02:49:55.8256325Z Using drake_cc_googletest_main.cc
2021-04-07T02:49:55.8256935Z 
2021-04-07T02:49:55.8257806Z [==========] Running 92 tests from 2 test suites.
~~~

**Comment by traversaro** [comment]
The isinf error is something related to glibc, I saw something similar in the past.
